"""empty message

Revision ID: 4b5747769fcf
Revises: 5f4c03131f29
Create Date: 2019-01-02 10:37:20.538313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b5747769fcf'
down_revision = '5f4c03131f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_authorId', 'posts', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_authorId', table_name='posts')
    # ### end Alembic commands ###
