"""empty message

Revision ID: 5f4c03131f29
Revises: cf956e6d39ed
Create Date: 2018-12-29 21:17:33.617346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f4c03131f29'
down_revision = 'cf956e6d39ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.String(length=191), nullable=True))
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=True))
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###
