"""empty message

Revision ID: cf956e6d39ed
Revises: 70ed2bbef3e6
Create Date: 2018-12-21 10:33:11.382712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf956e6d39ed'
down_revision = '70ed2bbef3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_kind', sa.Integer(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ti_tk_ui', 'comment_items', ['target_id', 'target_kind', 'user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_id', 'to_id', name='uk_from_to')
    )
    op.create_index('idx_time_to_from', 'contacts', ['created_at', 'to_id', 'from_id'], unique=False)
    op.create_index('idx_to_time_from', 'contacts', ['to_id', 'created_at', 'from_id'], unique=False)
    op.create_table('user_follow_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.drop_index('idx_ti_tk_ui', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('target_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('target_kind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ref_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_ti_tk_ui', 'comments', ['target_id', 'target_kind', 'user_id'], unique=False)
    op.drop_table('user_follow_stats')
    op.drop_index('idx_to_time_from', table_name='contacts')
    op.drop_index('idx_time_to_from', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('idx_ti_tk_ui', table_name='comment_items')
    op.drop_table('comment_items')
    # ### end Alembic commands ###
